### ISSUE TITLE
Add a warning on missing pages in pdfly cat

### ISSUE THREAD

**Issue by Lucas-C** [py-pdf/pdfly#33]
We want to produce a warning (on _stderr_) when a user attemps to use `pdfly cat`
to extract a range of pages that is **outside** the number of pages of the PDF document processed.

We already have a unit test regarding this, so this feature could considered DONE when this unit test will pass:
https://github.com/py-pdf/pdfly/blob/main/tests/test_extract_images.py#L20

**Comment by pavankalyan224847** [comment]
hello i would like to work on this issue can you please assign it to me

**Comment by pavankalyan224847** [comment]
can you assign this issue to me

**Comment by Lucas-C** [comment]
> hello i would like to work on this issue can you please assign it to me

Great! Sure, I just did so 🙂

Do you plan to work on this as part of https://hacktoberfest.com?

Also please tell us if you stop working on this, so that we can unassign this issue.

**Comment by pavankalyan224847** [comment]
Thank you for assigning me this issue and yes i want to work on this as a part of https://hacktoberfest.com

**Comment by Lucas-C** [comment]
Hi @pavankalyan224847

Are you still planning to work on this, or can we unassign you?

**Comment by pavankalyan224847** [comment]
please unassign this issue i'll comeback later

**Comment by Zingzy** [comment]
Hi, I would like to work on this issue as a part of hacktoberfest 2024, so please assign this issue to me

**Comment by Zingzy** [comment]
Hello @Lucas-C I made a PR #58 for this issue, please check 😄

**Comment by Lucas-C** [comment]
Closing this, it was implemented in https://github.com/py-pdf/pdfly/pull/58
