### ISSUE TITLE
Command x2pdf missing in version installed from PyPI

### ISSUE THREAD

**Issue by miso-belica** [py-pdf/pdfly#36]
Hello, thank you for the library. I was trying to use a command `pdfly x2pdf *.jpg -o merged.pdf` but it seems the version uploaded in PyPI does not have it. Can you please release a new version with this command? Thank you

**Comment by Lucas-C** [comment]
I think this is now solved:
```
$ pdfly --version
pdfly 0.3.3
  using pypdf==4.2.0

$ pdfly --help
...
│ x2pdf            Convert one or more files to PDF. Each file is a page.
```

**Comment by miso-belica** [comment]
Thank you, but in the meantime I found this web app which solves everything for me. https://pdfstandalone.com/

It is set of webassembly PDF tools running **locally in the browser** without the need to install anything.
