### ISSUE TITLE
ENH: Add an uncompress functionality

### ISSUE THREAD

**Issue by 3052** [py-pdf/pdfly#38]
Is it possible to uncompress PDF? similar to:

~~~sh
# uncompress
qpdf --stream-data=uncompress a.pdf b.pdf
# compress
qpdf b.pdf c.pdf
~~~

https://github.com/qpdf/qpdf/releases

**Comment by Lucas-C** [comment]
Hi @3052

No, currently `pdfly` does not offer such functionality

**Comment by Kaos599** [comment]
hey @MartinThoma, @Lucas-C i have tried working on this feature but i am not able to find out where you are referencing packages in pdfly?

**Comment by Lucas-C** [comment]
> i am not able to find out where you are referencing packages in pdfly?

You could intiate a new `.py` file in https://github.com/py-pdf/pdfly/tree/main/pdfly

And then reference it in https://github.com/py-pdf/pdfly/blob/main/pdfly/cli.py

**Comment by Kaos599** [comment]
@Lucas-C I have implemented the feature but i am having trouble linting it with black, my local system with black shows no need for reformatting while the CI run fails with Black error.

**Comment by Lucas-C** [comment]
> i am having trouble linting it with black, my local system with black shows no need for reformatting while the CI run fails with Black error.

What is the error you are facing exactly?

And what is your version of `black`?

On my side:
```
$ black --version
black, 24.10.0 (compiled: yes)
```

**Comment by Kaos599** [comment]
> > i am having trouble linting it with black, my local system with black shows no need for reformatting while the CI run fails with Black error.
> 
> What is the error you are facing exactly?
> 
> And what is your version of `black`?
> 
> On my side:
> 
> ```
> $ black --version
> black, 24.10.0 (compiled: yes)
> ```

From my tinkering, everything is compliant except the `I001` rule in ruff which checks for "Imports not at the top of the file." in the `cli.py` file

I dont know how but its somehow messing with black.

if i use `ruff format cli.py` it formats [these](https://github.com/Kaos599/pdfly/blob/ef39e2e26f87cd8436e7178d75cb20a7353fdafb/pdfly/cli.py#L7-L25).


And as for the version issue with black, i used github codespaces and that solved the issue.
