### ISSUE TITLE
ENH: Add a remove pages functionality

### ISSUE THREAD

**Issue by ebotiab** [py-pdf/pdfly#53]
Is it possible to remove PDF pages? It could be the reverse to the cat command:

```bash
pdfly rm with_pages_rm.pdf to_remove.pdf 1-4
```

**Comment by pubpub-zz** [comment]
this sound a good idea: can you propose a PR?

**Comment by ebotiab** [comment]
Sure!

**Comment by ebotiab** [comment]
I have added the rm funcionility now, the PR is pending to review

**Comment by ebotiab** [comment]
Hi, I have just added a comment in the PR with a user with write privileges

**Comment by Lucas-C** [comment]
Hi

I reviewed your PR @ebotiab

**Comment by Lucas-C** [comment]
Implemented by @ebotiab in PR #59
