### ISSUE TITLE
ENH: Add cat from file functionality

### ISSUE THREAD

**Issue by ebotiab** [py-pdf/pdfly#56]
It could be more convinient in some cases to store the files to concatenate into a file e.g. a csv rather than passing them as arguments in the cat command, for example, if there are a lot of pdfs to merge. For this a possible new command could be:

```bash
cat-from-csv "pdfs_data_to_merge.csv"  --filescol "col_with_file_paths" --pagescol "col_with_pages_to_cat".
```

**Comment by cyy-2024** [comment]
this is a good idea~I also think so.I will try on the issue.     :)

**Comment by ebotiab** [comment]
I can try to create PR on this, if you want

**Comment by Lucas-C** [comment]
I'm not sure that this really needs to be embedded in `pdfly`...

Fur such task, it may be better to combine `pdfly cat` with a CSV-parsing command like [xsv](https://github.com/BurntSushi/xsv) or [csvkit](https://csvkit.readthedocs.io/en/latest/), or simply to write a dedicated Python script.

Quoting _The UNIX Philosophy_ by Mike Gancarz:
> 1. Small is beautiful.
> 2. Make each program do one thing well.
> ...
> 9. Make every program a filter.
