### ISSUE TITLE
FN_PGRGS is required

### ISSUE THREAD

**Issue by EmperorArthur** [py-pdf/pdfly#60]
`pdfly cat --help` says "A file not followed by a page range means all the pages of the file."  However, page range is a required argument.

Edit:

The help output is also formatted extremely differently compared to the cat.py file.

![image](https://github.com/user-attachments/assets/c74abcb0-de9e-47c0-89cc-fb0805837a01)

**Comment by Lucas-C** [comment]
Hi @EmperorArthur

Thank you for the report

I opened PR https://github.com/py-pdf/pdfly/pull/62 to fix this
